__title__ = "plofeld"
__author__ = "JoschD"
__description__ = "Plotting functions for physical fields."
__url__ = "https://github.com/JoschD/plofeld"
__version__ = "0.0.1"
__author_email__ = "JoschD@github.com"
__license__ = "MIT"